# 턴어페이지 - 데이터 블로그

remote_theme             : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "contrast"

locale                   : "ko-KR"
title                    : "턴어페이지"
title_separator          : "|"
name                     : "턴어페이지"
description              : "데이터 분석가의 성장 블로그"
url                      : "https://leezcak.github.io"
baseurl                  : ""
repository               : "leezcak/leezcak.github.io"
masthead_title           : "턴어페이지"
breadcrumbs              : true
words_per_minute         : 150
enable_copy_code_button  : true
copyright                : "턴어페이지"

comments:
  provider               : "giscus"
  giscus:
    repo_id              : "R_kgDOPW_cSw"
    category_name        : "General"
    category_id          : "DIC_kwDOPW_cS84C3pA9"
    discussion_term      : "pathname"
    reactions_enabled    : "1"
    theme                : "light"
    strict               : "0"
    input_position       : "bottom"
    emit_metadata        : "1"
    lang                 : "ko"
    lazy                 : true

atom_feed:
  hide                   : false
search                   : true
search_full_content      : true
search_provider          : lunr

google_site_verification : "lWt3AlIe9LmK4I48gyLhlDzJinWQCD_6_vi686KseWY"
naver_site_verification  : ""

og_image                 : "/assets/images/og-default.png"
social:
  type                   : "Person"
  name                   : "턴어페이지"
  links:
    - "https://github.com/leezcak"
    - "https://www.linkedin.com/in/ireneyejin-lee/"

analytics:
  provider               : false

author:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ireneyejin-lee"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/leezcak"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:hmynmsrnl@gmail.com"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ireneyejin-lee/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/leezcak"

include:
  - _pages
exclude:
  - vendor
  - Gemfile
  - LICENSE
  - README
  - /docs
  - /test
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: "1..6"
  smart_quotes: "lsquo,rsquo,ldquo,rdquo"
  enable_coderay: false

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Asia/Seoul

paginate: 8
paginate_path: /page:num/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
      toc: true
      toc_label: "목차"
      toc_sticky: true
      sidebar:
        nav: "categories"
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "categories"
